# Configuration for probot/stale
# https://probot.github.io/apps/stale/

daysUntilStale: 60
daysUntilClose: 14
staleLabel: stale

markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed in 14 days if no further activity occurs.

closeComment: >
  This issue was closed because it has been inactive for 14 days since being
  marked as stale.

only: issues
exemptLabels:
  - pinned
  - security
