export const TOOL_VERBS: Record<string, string> = {
  browser: 'browsing',
  browser_exec: 'browsing',
  clarify: 'asking',
  computer_use: 'controlling',
  create_file: 'creating',
  cronjob: 'scheduling',
  delegate_task: 'delegating',
  delete_file: 'deleting',
  execute_code: 'executing',
  image_generate: 'generating',
  list_files: 'listing',
  memory: 'remembering',
  patch: 'patching',
  process: 'monitoring',
  read_file: 'reading',
  run_command: 'running',
  search_code: 'searching',
  search_files: 'searching',
  session_search: 'searching',
  skill_manage: 'saving skill',
  skill_view: 'loading skill',
  skills_list: 'listing skills',
  terminal: 'terminal',
  text_to_speech: 'speaking',
  todo: 'planning',
  tool_search: 'searching',
  vision_analyze: 'analyzing',
  web_extract: 'extracting',
  web_search: 'searching',
  write_file: 'writing'
}

export const VERBS = [
  'pondering',
  'contemplating',
  'musing',
  'cogitating',
  'ruminating',
  'deliberating',
  'mulling',
  'reflecting',
  'processing',
  'reasoning',
  'analyzing',
  'computing',
  'synthesizing',
  'formulating',
  'brainstorming'
]
