"""Suggested follow-up actions rendered as tappable buttons.

After the agent delivers its final reply, the gateway can offer the user a
small set of likely next actions as platform-native buttons (Telegram inline
keyboard) instead of making them type the follow-up.  Tapping one starts a
NEW turn seeded with that action's text — the same path a typed message
takes.

Two properties separate this from the existing interactive primitives
(``tools/approval.py``, ``tools/clarify_gateway.py``):

  * **Non-blocking.**  Approval and clarify block the agent thread on a
    ``threading.Event`` because the agent cannot proceed without an answer.
    Suggestions are offered *after* the turn is already finished, so there
    is nothing to unblock: no ``Event``, no timeout thread, no reaper.  A
    user who ignores the buttons costs nothing.

  * **Generated by a separate, cheaper model.**  The suggestions are NOT a
    tool the main model calls.  Asking the expensive main model to decide
    "should I offer buttons, and which ones" would add reasoning and output
    tokens to every single turn.  Instead the finished reply is handed to
    the shared auxiliary router (:mod:`agent.auxiliary_client`) under the
    ``suggested_actions`` task, which resolves through the same
    provider/model chain that already backs compression and vision — so an
    operator can point it at a small local model, a ``:free`` OpenRouter
    SKU, or a cheap flash tier via ``auxiliary.suggested_actions.model``
    without touching the main model at all.

The button label IS the text injected on tap.  There is deliberately no
separate hidden payload: a button that reads "Deploy to staging" can only
ever send "Deploy to staging", so what the user approves by tapping is
exactly what the agent receives.

That property is also the containment for the obvious injection worry.  The
reply text handed to the auxiliary model is not trusted — it can carry
whatever a web page or tool output persuaded the agent to repeat — so a
crafted reply could in principle steer the suggestion model into proposing
an action the user did not want.  What it cannot do is hide: the label is
capped at ``MAX_LABEL_LEN``, stripped of control and bidi characters, and
rendered verbatim as the thing that will be sent.  A malicious suggestion
therefore has to survive being read by the user, who must then tap it, and
it re-enters as an ordinary user message — subject to the same exec-approval
gate as anything they could have typed themselves.  Nothing here can act on
its own.

Disabled by default (``gateway.suggested_actions.enabled``) — it adds one
auxiliary LLM call per turn, which no existing install has budgeted for.
"""

from __future__ import annotations

import json
import logging
import re
import threading
import time
import uuid
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


# =========================================================================
# Limits
# =========================================================================

# Telegram truncates long inline-button labels on mobile, and a wall of
# choices defeats the point of a shortcut. Four is what the exec-approval
# keyboard already tops out at (2x2 rows).
MAX_ACTIONS = 4

# One action is a legitimate result, not a degenerate one: "confirm and
# proceed" is exactly the case where a single tappable button beats typing.
MIN_ACTIONS = 1

# Labels longer than this get dropped rather than truncated — a clipped
# label ("Deploy to prod and rest…") is worse than no button, because the
# user taps it without seeing what it actually sends.
MAX_LABEL_LEN = 48

# Cap the reply text handed to the auxiliary model. Suggestions come from
# the shape of the answer, not its every detail, and an unbounded tail
# would make the "cheap" call not cheap.
MAX_CONTEXT_CHARS = 2000

# Bound the registry without a reaper thread: each session keeps only its
# most recent set (an older set's buttons are stale the moment a new reply
# lands), and the total is capped so an idle multi-chat gateway cannot grow
# unboundedly.
MAX_TRACKED_SESSIONS = 512

# A set nobody taps and nobody supersedes (a quiet 1:1 chat that never gets
# a follow-up reply) would otherwise live until the eviction cap forces it
# out — which, in a lightly used gateway, can be a long time. Tapping a
# week-old button and getting a turn seeded from a conversation that has
# moved on is a worse outcome than tapping it and being told it expired.
# 10 minutes matches the class of feature (see the sibling action-button
# PR #95594, which documents the same window).
DEFAULT_TTL_SECONDS = 600.0

# Four labels of at most MAX_LABEL_LEN characters need well under 100 tokens
# of JSON, but small models routinely narrate before answering and that prose
# is billed as completion. Measured in production: a 4-action response spent
# 193 tokens with zero reported reasoning tokens — the rest was visible
# thinking that ``strip_think_blocks`` then discarded. A cap that clips such a
# response mid-array turns into "no buttons this turn" with nothing to show
# for the spend, so leave real headroom; unused budget is never billed.
DEFAULT_MAX_TOKENS = 600

# Control characters, zero-width joiners and bidi overrides must never reach
# a button label: they let a rendered label differ from the text it sends.
_UNSAFE_CHARS = re.compile(
    r"[\x00-\x1f\x7f\u200b-\u200f\u2028\u2029\u202a-\u202e\u2066-\u2069]"
)


# Two gates, stated as gates rather than as preferences, because the failure
# mode in production was not bad wording — it was answering the wrong
# question. Told to propose "actions the user would take", the model proposed
# real-world ones: a reply recommending dishes produced "Order the grilled
# scallops", which the assistant cannot do and no user would ever send it.
# The second failure was mechanical mirroring: any list in the reply came back
# as one button per item, so informational answers always produced a full set.
# Hence the explicit "most replies deserve NO buttons" and the negative
# examples — abstaining has to be the modelled default, not a permitted one.
_PROMPT = """\
You choose reply-buttons for a chat assistant. Below is the user's last
message and the assistant's reply. Decide whether to offer the user any
one-tap follow-up messages.

Most replies deserve NO buttons. Returning [] is the correct answer far more
often than not, and an empty list is never a failure.

Offer buttons ONLY if BOTH gates pass.

Gate 1 — is something still open?
The reply must leave a decision or a next step hanging: it asks the user a
question, offers to do something, presents alternatives to choose between, or
reports a problem the assistant could act on next.
If the reply simply answered the question — a fact, an explanation, a
recommendation, a list of options to consider, advice — then nothing is open.
Return [].

Gate 2 — can THIS ASSISTANT carry the action out?
It is a chat assistant: it can answer, look things up, write and run code,
edit files, and use its tools. It CANNOT do anything in the physical world.
An action the user performs themselves — ordering food, buying, going
somewhere, cooking, meeting someone — is never a valid button, even when the
reply is all about that. Return [].

Also never propose:
- an item copied out of a list in the reply, turned into a command
- vague filler like "tell me more", "explain", "what else"
- anything the reply already did

Each action must be a short imperative message the user would send next, at
most {max_label} characters, no numbering, no quotes, no trailing period.
Order them most likely first. At most {max_actions}. Write them in the same
language as the reply.

Examples:
reply "I found 3 uncommitted files. Want me to commit them?" -> ["Commit them"]
reply "The deploy failed on the lint step. Log is at /tmp/deploy.log" -> ["Show the lint errors", "Retry the deploy"]
reply "The capital of France is Paris." -> []
reply "Here are three good restaurants nearby: A, B, C." -> []
reply "I'd order the scallops, the shrimp and the snails." -> []

Respond with ONLY a JSON array of strings. No prose, no code fence.

<user_message>
{user_text}
</user_message>

<assistant_reply>
{reply_text}
</assistant_reply>
"""


# =========================================================================
# Config
# =========================================================================

def _gateway_config() -> Dict[str, Any]:
    """Return the ``gateway.suggested_actions`` config block, or {}."""
    try:
        from hermes_cli.config import load_config_readonly as _load_config
        cfg = _load_config()  # read-only: .get() only, never mutated
    except Exception:
        return {}
    if not isinstance(cfg, dict):
        return {}
    gw = cfg.get("gateway", {})
    if not isinstance(gw, dict):
        return {}
    block = gw.get("suggested_actions", {})
    return block if isinstance(block, dict) else {}


def is_enabled() -> bool:
    """True when the gateway should offer suggested actions.

    Off unless explicitly enabled: the feature spends an auxiliary LLM call
    on every delivered reply, so an install that never opted in must not
    start paying for it after an upgrade.
    """
    return bool(_gateway_config().get("enabled", False))


def max_actions() -> int:
    """Configured ceiling on offered actions, clamped to [1, MAX_ACTIONS]."""
    try:
        raw = int(_gateway_config().get("max_actions", MAX_ACTIONS))
    except (TypeError, ValueError):
        return MAX_ACTIONS
    return max(MIN_ACTIONS, min(raw, MAX_ACTIONS))


# =========================================================================
# Normalization
# =========================================================================

def normalize_actions(raw: Any, limit: Optional[int] = None) -> List[str]:
    """Coerce a model-produced value into a clean list of button labels.

    Applies the same defensive flattening as ``clarify_tool._flatten_choice``
    — models emit ``[{"label": ...}]`` about as often as bare strings — then
    drops anything that cannot be safely rendered on a button: empty text,
    over-long labels, control/bidi characters, and duplicates (a keyboard
    with the same action twice is a bug the user has to think about).
    """
    if limit is None:
        limit = MAX_ACTIONS

    if isinstance(raw, str):
        raw = [raw]
    if not isinstance(raw, (list, tuple)):
        return []

    cleaned: List[str] = []
    seen: set = set()
    for item in raw:
        label = _flatten(item)
        if not label:
            continue
        # Collapse internal whitespace so a multi-line emission cannot
        # render as a one-line button that sends something taller.
        label = " ".join(label.split())
        if _UNSAFE_CHARS.search(label):
            continue
        if len(label) > MAX_LABEL_LEN:
            continue
        key = label.casefold()
        if key in seen:
            continue
        seen.add(key)
        cleaned.append(label)
        if len(cleaned) >= limit:
            break
    return cleaned


def _flatten(value: Any) -> str:
    """Reduce one model-emitted action to its display string."""
    if value is None:
        return ""
    if isinstance(value, str):
        return value.strip()
    if isinstance(value, dict):
        for key in ("label", "action", "text", "title", "description"):
            candidate = value.get(key)
            if isinstance(candidate, str) and candidate.strip():
                return candidate.strip()
        return ""
    return ""


def _parse_response(content: str, limit: int) -> List[str]:
    """Extract the JSON array from an auxiliary-model response."""
    text = (content or "").strip()
    if not text:
        return []

    # Tolerate a fenced block even though the prompt forbids one — small
    # models add fences habitually, and refusing them would silently cost
    # every suggestion on those backends.
    if text.startswith("```"):
        text = re.sub(r"^```[a-zA-Z]*\s*", "", text)
        text = re.sub(r"\s*```$", "", text).strip()

    try:
        return normalize_actions(json.loads(text), limit)
    except (json.JSONDecodeError, TypeError):
        pass

    # Last resort: pull the first bracketed span out of surrounding prose.
    # Non-greedy: a schema-conforming response is a flat array of strings,
    # so the first "]" really does close it. The earlier greedy version
    # spanned from the first "[" to the LAST "]" in the text, so a reply
    # like "sure! [1] and also [2]" over-captured into "[1] and also [2]"
    # and failed to parse as JSON — losing suggestions the model actually
    # returned, on exactly the narrating-small-model responses this
    # fallback exists for.
    match = re.search(r"\[.*?\]", text, re.DOTALL)
    if match:
        try:
            return normalize_actions(json.loads(match.group(0)), limit)
        except (json.JSONDecodeError, TypeError):
            return []
    return []


# =========================================================================
# Generation
# =========================================================================

def generate(reply_text: str, user_text: str = "") -> List[str]:
    """Ask the auxiliary model for likely next actions. Never raises.

    Returns ``[]`` on any failure — no configured backend, a timeout, a
    malformed response.  The reply has already been delivered by the time
    this runs, so a failure here must never surface to the user as an
    error; it just means no buttons this turn.
    """
    reply_text = (reply_text or "").strip()
    if not reply_text:
        return []

    limit = max_actions()
    prompt = _PROMPT.format(
        max_actions=limit,
        max_label=MAX_LABEL_LEN,
        user_text=_clip(user_text),
        reply_text=_clip(reply_text),
    )

    try:
        from agent.auxiliary_client import call_llm

        # No explicit ``timeout``: a caller-supplied value overrides
        # ``auxiliary.suggested_actions.timeout``, and this task's whole point
        # is that the operator can tune it. temperature=0 is safe to hardcode
        # — the auxiliary client strips it for models that reject sampling
        # params.
        response = call_llm(
            task="suggested_actions",
            messages=[{"role": "user", "content": prompt}],
            max_tokens=DEFAULT_MAX_TOKENS,
            temperature=0,
        )
    except Exception as exc:
        logger.debug("suggested-actions generation failed: %s", exc)
        return []

    try:
        content = (
            response.choices[0].message.content
            if hasattr(response, "choices")
            else str(response)
        ) or ""
    except (AttributeError, IndexError, TypeError) as exc:
        logger.debug("suggested-actions response unreadable: %s", exc)
        return []

    # A response cut off at the token cap usually ends mid-array, so parsing
    # yields nothing and the turn silently loses its buttons. Say so rather
    # than let it look like the model simply had no suggestions — the two
    # are indistinguishable downstream, and only one of them is a problem
    # the operator can fix (by raising the cap).
    try:
        if getattr(response.choices[0], "finish_reason", None) == "length":
            logger.info(
                "suggested-actions response hit the %d-token cap and was "
                "truncated; raise auxiliary.suggested_actions max tokens if "
                "this recurs",
                DEFAULT_MAX_TOKENS,
            )
    except (AttributeError, IndexError, TypeError):
        pass

    # Reasoning models leak <think> blocks into content on several
    # backends; the shared stripper is what compression uses for the
    # same problem.
    try:
        from agent.agent_runtime_helpers import strip_think_blocks
        content = strip_think_blocks(None, content)
    except Exception:
        pass

    return _parse_response(content, limit)


def _clip(text: str) -> str:
    text = (text or "").strip()
    if len(text) <= MAX_CONTEXT_CHARS:
        return text
    return text[:MAX_CONTEXT_CHARS] + "\n[…truncated]"


# =========================================================================
# Registry
# =========================================================================

@dataclass
class _ActionSet:
    """One delivered set of suggestions, awaiting a tap that may never come."""
    set_id: str
    session_key: str
    chat_id: str
    actions: List[str]
    source: Any = None
    metadata: Optional[Dict[str, Any]] = field(default=None)
    expires_at: float = field(default=0.0)

    def is_expired(self) -> bool:
        return time.monotonic() >= self.expires_at


_lock = threading.RLock()
_sets: Dict[str, _ActionSet] = {}
# session_key → set_id of that session's most recent (only live) set.
_by_session: Dict[str, str] = {}


def register(
    session_key: str,
    chat_id: str,
    actions: List[str],
    source: Any = None,
    metadata: Optional[Dict[str, Any]] = None,
    ttl_seconds: float = DEFAULT_TTL_SECONDS,
) -> Optional[str]:
    """Store one action set and return its short id, or None if empty.

    Registering supersedes any previous set for the same session: once a
    newer reply has been delivered, the older message's buttons refer to a
    conversation state that has moved on. ``ttl_seconds`` bounds how long an
    UNsuperseded set stays tappable — a quiet chat that never gets a
    follow-up reply would otherwise hold its buttons live indefinitely.
    """
    actions = normalize_actions(actions, max_actions())
    if len(actions) < MIN_ACTIONS:
        return None

    set_id = uuid.uuid4().hex[:10]
    entry = _ActionSet(
        set_id=set_id,
        session_key=session_key,
        chat_id=str(chat_id),
        actions=actions,
        source=source,
        metadata=dict(metadata) if metadata else None,
        expires_at=time.monotonic() + max(0.0, ttl_seconds),
    )
    with _lock:
        previous = _by_session.get(session_key)
        if previous:
            _sets.pop(previous, None)
        _sets[set_id] = entry
        _by_session[session_key] = set_id
        _evict_locked()
    return set_id


def _evict_locked() -> None:
    """Drop the oldest sets once the global cap is exceeded.

    dicts preserve insertion order, so the head is the least recently
    registered. This is the whole memory bound — there is no timer thread,
    because an unclaimed set costs a few hundred bytes and no wakeups.
    """
    while len(_sets) > MAX_TRACKED_SESSIONS:
        oldest_id, oldest = next(iter(_sets.items()))
        _sets.pop(oldest_id, None)
        if _by_session.get(oldest.session_key) == oldest_id:
            _by_session.pop(oldest.session_key, None)


def get(set_id: str) -> Optional[_ActionSet]:
    """Return the set for ``set_id`` without consuming it, unless it expired.

    An expired set is dropped here rather than left for the eviction sweep —
    treating it as absent is what makes ``resolve()`` on a stale tap report
    "no longer available" instead of quietly reviving it.
    """
    with _lock:
        entry = _sets.get(set_id)
        if entry is None:
            return None
        if entry.is_expired():
            _sets.pop(set_id, None)
            if _by_session.get(entry.session_key) == set_id:
                _by_session.pop(entry.session_key, None)
            return None
        return entry


def resolve(set_id: str, index: int) -> Optional[str]:
    """Consume one set and return the tapped action's text.

    Pop-once: the whole set is removed, so a double-tap (or two people
    tapping different buttons on the same message in a group) starts one
    follow-up turn, not two.  A tap on a superseded or already-used set
    returns ``None`` and the caller tells the user it expired.
    """
    with _lock:
        entry = _sets.get(set_id)
        if entry is None:
            return None
        if entry.is_expired():
            _sets.pop(set_id, None)
            if _by_session.get(entry.session_key) == set_id:
                _by_session.pop(entry.session_key, None)
            return None
        if not (0 <= index < len(entry.actions)):
            return None
        _sets.pop(set_id, None)
        if _by_session.get(entry.session_key) == set_id:
            _by_session.pop(entry.session_key, None)
        return entry.actions[index]


def clear_session(session_key: str) -> None:
    """Forget a session's pending set (session reset / gateway teardown)."""
    with _lock:
        set_id = _by_session.pop(session_key, None)
        if set_id:
            _sets.pop(set_id, None)


def reset() -> None:
    """Drop all state. Test hook."""
    with _lock:
        _sets.clear()
        _by_session.clear()
