"""Structural gates for the mcp_tool shard index and compatibility seam."""

import base64
from pathlib import Path
import inspect
import json
import os
import pickle
import subprocess
import sys

import tools.mcp_tool as mcp_tool
from tools import mcp_tool_shards


MAX_LINES = 2_000


def _binary_line_count(path: Path) -> int:
    return path.read_bytes().count(bytes([10]))


def test_mcp_tool_facade_and_indexed_shards_obey_2k_law():
    facade = Path(mcp_tool.__file__)
    assert _binary_line_count(facade) <= MAX_LINES

    assert mcp_tool_shards.SHARD_INDEX
    for shard_name, shard_path, exported_names in mcp_tool_shards.SHARD_INDEX:
        path = Path(shard_path)
        assert path.exists(), shard_name
        assert _binary_line_count(path) <= MAX_LINES, shard_name
        for exported_name in exported_names:
            assert hasattr(mcp_tool, exported_name), (shard_name, exported_name)


def test_mcp_tool_shard_index_preserves_original_module_seam():
    assert mcp_tool._make_tool_handler.__module__ == "tools.mcp_tool"
    assert mcp_tool._sanitize_mcp_result_value.__module__ == "tools.mcp_tool"
    assert mcp_tool._make_list_resources_handler.__module__ == "tools.mcp_tool"
    assert mcp_tool._make_read_resource_handler.__module__ == "tools.mcp_tool"
    assert mcp_tool._make_list_prompts_handler.__module__ == "tools.mcp_tool"
    assert mcp_tool._make_get_prompt_handler.__module__ == "tools.mcp_tool"


def test_exported_mcp_classes_remain_source_introspectable():
    """Shard relocation must not make public classes opaque to inspect."""
    classes = {
        "MCPServerTask": "tools.mcp_tool_shards.server_transport",
        "_MCPServerTaskTransportMixin": "tools.mcp_tool_shards.server_transport",
        "SamplingHandler": "tools.mcp_tool_shards.server_lifecycle",
        "ElicitationHandler": "tools.mcp_tool_shards.server_lifecycle",
        "_MCPServerTaskLifecycleMixin": "tools.mcp_tool_shards.server_lifecycle",
    }
    for name, source_module in classes.items():
        cls = getattr(mcp_tool, name)
        assert cls.__module__ == source_module
        source = inspect.getsource(cls)
        assert f"class {name}" in source

    assert "def __init__" in inspect.getsource(mcp_tool._MCPServerTaskLifecycleMixin)
    assert "async def _run_stdio" in inspect.getsource(
        mcp_tool.MCPServerTask._run_stdio
    )
    assert pickle.loads(pickle.dumps(mcp_tool.MCPServerTask)) is mcp_tool.MCPServerTask


def test_exported_mcp_classes_pickle_parent_bytes_in_fresh_child():
    """Parent-produced class bytes resolve in a facade-cold child process."""
    classes = {
        "MCPServerTask": "tools.mcp_tool_shards.server_transport",
        "_MCPServerTaskTransportMixin": "tools.mcp_tool_shards.server_transport",
        "SamplingHandler": "tools.mcp_tool_shards.server_lifecycle",
        "ElicitationHandler": "tools.mcp_tool_shards.server_lifecycle",
        "_MCPServerTaskLifecycleMixin": "tools.mcp_tool_shards.server_lifecycle",
    }
    parent_payload = []
    for class_name, module_name in classes.items():
        cls = getattr(mcp_tool, class_name)
        assert cls.__module__ == module_name
        parent_payload.append({
            "class_name": class_name,
            "module_name": module_name,
            "pickle_b64": base64.b64encode(pickle.dumps(cls)).decode("ascii"),
        })

    repo_root = Path(mcp_tool.__file__).resolve().parents[1]
    script = """
import base64
import importlib
import json
import pickle
import sys

assert "tools.mcp_tool" not in sys.modules
records = json.loads(sys.stdin.buffer.read())
assert len(records) == 5
for record in records:
    # These bytes are generated by this test's parent from imported facade
    # classes; the child intentionally exercises only that controlled payload.
    restored = pickle.loads(base64.b64decode(record["pickle_b64"]))
    assert restored.__module__ == record["module_name"]
    assert restored.__name__ == record["class_name"]
    module = importlib.import_module(record["module_name"])
    assert getattr(module, record["class_name"]) is restored
print("parent-child-pickle: ok")
"""
    env = os.environ.copy()
    env.pop("PYTHONPATH", None)
    result = subprocess.run(
        [sys.executable, "-c", script],
        cwd=repo_root,
        env=env,
        input=json.dumps(parent_payload).encode("utf-8"),
        capture_output=True,
        check=False,
    )
    assert result.returncode == 0, (
        f"parent-child pickle probe failed (rc={result.returncode})\\n"
        f"stdout: {result.stdout.decode(errors='replace')}\\n"
        f"stderr: {result.stderr.decode(errors='replace')}"
    )
    assert b"parent-child-pickle: ok" in result.stdout
