"""Hindsight's declared config surface — rendered by the generic desktop panel."""

from plugins.memory.config_schema import (
    KIND_BOOL,
    KIND_NUMBER,
    KIND_SECRET,
    KIND_SELECT,
    KIND_TEXT,
    KIND_JSON,
    ProviderConfigSchema,
    ProviderField,
    ProviderFieldOption,
)

CONFIG_SCHEMA = ProviderConfigSchema(
    name="hindsight",
    label="Hindsight",
    fields=(
        ProviderField(
            key="mode",
            label="Mode",
            kind=KIND_SELECT,
            default="cloud",
            description="How Hermes connects to Hindsight.",
            options=(
                ProviderFieldOption(
                    "cloud",
                    "Cloud",
                    "Hindsight Cloud API (lightweight, just needs an API key)",
                ),
                ProviderFieldOption(
                    "local_embedded",
                    "Local Embedded",
                    "Run Hindsight locally with an embedded LLM",
                ),
                ProviderFieldOption(
                    "local_external",
                    "Local External",
                    "Connect to an existing Hindsight instance",
                ),
            ),
            inline=True,
        ),
        # --- Cloud mode fields ---
        ProviderField(
            key="api_url",
            label="Cloud API URL",
            kind=KIND_TEXT,
            default="https://api.hindsight.vectorize.io",
            aliases=("apiUrl",),
            env_fallbacks=("HINDSIGHT_API_URL",),
            inline=True,
            when={"mode": "cloud"},
        ),
        ProviderField(
            key="api_key",
            label="Cloud API key",
            kind=KIND_SECRET,
            env_key="HINDSIGHT_API_KEY",
            description="Used to authenticate with the Hindsight Cloud API.",
            placeholder="Enter Hindsight API key",
            inline=True,
            when={"mode": "cloud"},
        ),
        # --- Local External mode fields ---
        ProviderField(
            key="api_url",
            label="Local API URL",
            kind=KIND_TEXT,
            default="http://localhost:8000",
            aliases=("apiUrl",),
            env_fallbacks=("HINDSIGHT_API_URL",),
            when={"mode": "local_external"},
        ),
        ProviderField(
            key="api_key",
            label="Local API key",
            kind=KIND_SECRET,
            env_key="HINDSIGHT_API_KEY",
            description="API key for the local Hindsight instance (optional).",
            inline=True,
            when={"mode": "local_external"},
        ),
        # --- Local Embedded mode fields ---
        ProviderField(
            key="llm_provider",
            label="LLM provider",
            kind=KIND_SELECT,
            default="openai",
            description="LLM provider for the embedded Hindsight instance.",
            options=(
                ProviderFieldOption("openai", "OpenAI"),
                ProviderFieldOption("anthropic", "Anthropic"),
                ProviderFieldOption("gemini", "Google Gemini"),
                ProviderFieldOption("groq", "Groq"),
                ProviderFieldOption("openrouter", "OpenRouter"),
                ProviderFieldOption("minimax", "MiniMax"),
                ProviderFieldOption("ollama", "Ollama"),
                ProviderFieldOption("lmstudio", "LM Studio"),
                ProviderFieldOption("openai_compatible", "OpenAI Compatible"),
            ),
            when={"mode": "local_embedded"},
        ),
        ProviderField(
            key="llm_base_url",
            label="Endpoint URL",
            kind=KIND_TEXT,
            default="",
            description="LLM endpoint URL (e.g. http://192.168.1.10:8080/v1).",
            when={"mode": "local_embedded", "llm_provider": "openai_compatible"},
        ),
        ProviderField(
            key="llm_model",
            label="LLM model",
            kind=KIND_TEXT,
            default="gpt-4o-mini",
            description="LLM model to use.",
            when={"mode": "local_embedded"},
        ),
        ProviderField(
            key="llm_api_key",
            label="LLM API key",
            kind=KIND_SECRET,
            env_key="HINDSIGHT_LLM_API_KEY",
            description="LLM API key (optional for openai_compatible).",
            when={"mode": "local_embedded"},
        ),
        ProviderField(
            key="idle_timeout",
            label="Idle timeout (seconds)",
            kind=KIND_NUMBER,
            default="300",
            description="Embedded daemon idle timeout in seconds (0 disables auto-shutdown).",
            when={"mode": "local_embedded"},
        ),
        ProviderField(
            key="port_health_grace_timeout",
            label="Port health grace timeout",
            kind=KIND_TEXT,
            default="",
            description="Seconds to wait for a slow daemon /health before treating it as stale (blank uses 30s default).",
            when={"mode": "local_embedded"},
        ),
        # --- Shared fields (all modes) ---
        ProviderField(
            key="bank_id",
            label="Bank ID",
            kind=KIND_TEXT,
            default="hermes",
            aliases=("bankId",),
            inline=True,
        ),
        ProviderField(
            key="bank_id_template",
            label="Bank ID template",
            kind=KIND_TEXT,
            default="",
            description="Optional template to derive bank_id dynamically. Placeholders: {profile}, {workspace}, {platform}, {user}, {session}. Example: hermes-{profile}",
        ),
        ProviderField(
            key="bank_mission",
            label="Bank mission",
            kind=KIND_TEXT,
            default="",
            description="Mission/purpose description for the memory bank.",
        ),
        ProviderField(
            key="bank_retain_mission",
            label="Retain mission prompt",
            kind=KIND_TEXT,
            default="",
            description="Custom extraction prompt for memory retention.",
        ),
        ProviderField(
            key="recall_budget",
            label="Recall budget",
            kind=KIND_SELECT,
            default="mid",
            aliases=("budget",),
            options=(
                ProviderFieldOption("low", "Low"),
                ProviderFieldOption("mid", "Mid"),
                ProviderFieldOption("high", "High"),
            ),
            inline=True,
        ),
        ProviderField(
            key="memory_mode",
            label="Memory integration mode",
            kind=KIND_SELECT,
            default="hybrid",
            description="How memories are integrated into conversations.",
            options=(
                ProviderFieldOption("hybrid", "Hybrid"),
                ProviderFieldOption("context", "Context only"),
                ProviderFieldOption("tools", "Tool calls only"),
            ),
        ),
        ProviderField(
            key="recall_prefetch_method",
            label="Auto-recall method",
            kind=KIND_SELECT,
            default="recall",
            description="How to auto-recall memories before each turn.",
            options=(
                ProviderFieldOption("recall", "Recall"),
                ProviderFieldOption("reflect", "Reflect"),
            ),
        ),
        ProviderField(
            key="retain_tags",
            label="Retain tags",
            kind=KIND_TEXT,
            default="",
            description="Default tags applied to retained memories (comma-separated).",
        ),
        ProviderField(
            key="observation_scopes",
            label="Observation scopes",
            kind=KIND_TEXT,
            default="",
            description="How observations are scoped during consolidation: 'combined' (default), 'per_tag', 'all_combinations', or a JSON list of tag-lists.",
        ),
        ProviderField(
            key="retain_source",
            label="Retain source",
            kind=KIND_TEXT,
            default="",
            description="Metadata source value attached to retained memories.",
        ),
        ProviderField(
            key="retain_user_prefix",
            label="User prefix",
            kind=KIND_TEXT,
            default="User",
            description="Label used before user turns in retained transcripts.",
        ),
        ProviderField(
            key="retain_assistant_prefix",
            label="Assistant prefix",
            kind=KIND_TEXT,
            default="Assistant",
            description="Label used before assistant turns in retained transcripts.",
        ),
        ProviderField(
            key="recall_tags",
            label="Recall tags filter",
            kind=KIND_TEXT,
            default="",
            description="Tags to filter when searching memories (comma-separated).",
        ),
        ProviderField(
            key="recall_tags_match",
            label="Recall tags match mode",
            kind=KIND_SELECT,
            default="any",
            description="Tag matching mode for recall.",
            options=(
                ProviderFieldOption("any", "Any"),
                ProviderFieldOption("all", "All"),
                ProviderFieldOption("any_strict", "Any Strict"),
                ProviderFieldOption("all_strict", "All Strict"),
            ),
        ),
        ProviderField(
            key="recall_types",
            label="Recall types",
            kind=KIND_TEXT,
            default="observation",
            description="Fact types to surface on recall — applies to both auto-recall and the hindsight_recall tool (comma-separated or list). Defaults to observation.",
        ),
        ProviderField(
            key="auto_recall",
            label="Auto-recall",
            kind=KIND_BOOL,
            default="true",
            description="Automatically recall memories before each turn.",
        ),
        ProviderField(
            key="auto_retain",
            label="Auto-retain",
            kind=KIND_BOOL,
            default="true",
            description="Automatically retain conversation turns.",
        ),
        ProviderField(
            key="retain_every_n_turns",
            label="Retain every N turns",
            kind=KIND_NUMBER,
            default="1",
            description="Retain every N turns (1 = every turn).",
        ),
        ProviderField(
            key="retain_async",
            label="Async retain",
            kind=KIND_BOOL,
            default="true",
            description="Process retain asynchronously on the Hindsight server.",
        ),
        ProviderField(
            key="prefetch_waits_for_retain",
            label="Prefetch waits for retain",
            kind=KIND_BOOL,
            default="true",
            description="Have the background next-turn prefetch wait for the just-completed retain to become recall-visible before recalling.",
        ),
        ProviderField(
            key="prefetch_retain_drain_timeout",
            label="Prefetch drain timeout (seconds)",
            kind=KIND_NUMBER,
            default="10.0",
            description="Max seconds the background prefetch waits for the retain to become recall-visible before recalling anyway.",
        ),
        ProviderField(
            key="retain_context",
            label="Retain context",
            kind=KIND_TEXT,
            default="conversation between Hermes Agent and the User",
            description="Context label for retained memories.",
        ),
        ProviderField(
            key="recall_max_tokens",
            label="Recall max tokens",
            kind=KIND_NUMBER,
            default="4096",
            description="Maximum tokens for recall results.",
        ),
        ProviderField(
            key="recall_max_input_chars",
            label="Recall max input chars",
            kind=KIND_NUMBER,
            default="800",
            description="Maximum input query length for auto-recall.",
        ),
        ProviderField(
            key="recall_prompt_preamble",
            label="Recall prompt preamble",
            kind=KIND_TEXT,
            default="",
            description="Custom preamble for recalled memories in context.",
        ),
        ProviderField(
            key="timeout",
            label="API timeout (seconds)",
            kind=KIND_NUMBER,
            default="30",
            description="API request timeout in seconds.",
        ),
    ),
)