#!/bin/sh
set -eu

exec /usr/bin/python3 -I -c \
  'import runpy,sys; sys.path.insert(0,"/usr/lib/muncho-release-updater"); sys.argv=sys.argv[1:]; runpy.run_module("scripts.canary.production_release_rotation_stager_launcher",run_name="__main__")' \
  muncho-release-unit-input-rotation-stager "$@"
