from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Protocol


class Verdict(str, Enum):
    CLEAR = "clear"
    DUPLICATE = "duplicate"
    ASSIGNED = "assigned"
    CLA_REQUIRED = "cla_required"
    AI_POLICY_REJECT = "ai_policy_reject"
    NOT_FOUND = "not_found"


class GitHubReader(Protocol):
    def get_issue(self, owner: str, repo: str, number: int) -> dict | None: ...
    def get_issue_timeline(self, owner: str, repo: str, number: int) -> list[dict]: ...
    def get_repo_file_text(self, owner: str, repo: str, path: str) -> str | None: ...


CONTRIBUTING_PATHS = ["CONTRIBUTING.md", ".github/CONTRIBUTING.md", "docs/CONTRIBUTING.md"]
AGENTS_PATHS = ["AGENTS.md", ".github/AGENTS.md"]
CLA_MARKERS = ["contributor license agreement", "cla-assistant", "sign the cla"]
DCO_MARKERS = ["developer certificate of origin", "signed-off-by"]

# Grounded in real CONTRIBUTING.md text, not invented — see
# internal-docs/harness/org-awareness-and-voice-design.md (private repo)
# for the research this implements. Checked in order: reject beats
# disclose beats constrain, because a real project can state more than
# one at once (paperless-ngx requires attribution AND rejects
# majority-AI PRs — reject is the one that actually changes the verdict).
AI_POLICY_REJECT_MARKERS = [
    "will not accept ai-generated",
    "will not accept ai generated",
    "will not accept prs that are entirely or mostly ai",
    "will not accept pull requests that are entirely or mostly ai",
    "do not accept ai-generated",
    "do not accept ai generated",
    "not accept pull requests generated by ai",
    "not accept prs generated by ai",
    "not accepting ai-generated",
    "no ai-generated pull requests",
    "no ai-generated code",
    "prohibit the use of ai-generated code",
    "ai-generated contributions are not accepted",
]
AI_POLICY_DISCLOSE_MARKERS = [
    "must be clearly marked as",
    "clearly attributed as such",
    "disclose the use of ai",
    "disclose if you used ai",
    "disclose ai assistance",
    "must disclose",
    "label ai-generated",
    "mark the slop",
]
AI_POLICY_CONSTRAIN_MARKERS = [
    "understand the core ideas",
    "must understand and test",
    "you must understand the code",
    "should understand the code",
    "ai tools must be supervised",
    "review all ai-generated code",
    "understand end-to-end",
]


@dataclass
class ScreenResult:
    owner: str
    repo: str
    issue: int
    verdict: Verdict
    reasons: list[str] = field(default_factory=list)
    evidence: dict = field(default_factory=dict)
    checked_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

    def to_dict(self) -> dict:
        d = dict(self.__dict__)
        d["verdict"] = self.verdict.value
        return d


def _find_duplicate_prs(timeline: list[dict]) -> list[str]:
    urls = []
    for event in timeline:
        if event.get("event") != "cross-referenced":
            continue
        pr_issue = event.get("source", {}).get("issue", {})
        if "pull_request" in pr_issue and pr_issue.get("html_url"):
            urls.append(pr_issue["html_url"])
    return urls


def _detect_contribution_norm(text: str) -> str | None:
    lowered = text.lower()
    if any(marker in lowered for marker in CLA_MARKERS):
        return "cla"
    if any(marker in lowered for marker in DCO_MARKERS):
        return "dco"
    return None


def _detect_ai_contribution_policy(text: str) -> str | None:
    """Classify a repo's stated stance on AI-assisted contributions.

    Three-way split, not invented — the real shape a 67-project survey
    found orgs actually use (reject outright / require disclosure /
    constrain behavior), per
    internal-docs/harness/org-awareness-and-voice-design.md. Returns
    None ("unstated") when no marker matches — the common case, and not
    itself a blocker.
    """
    lowered = text.lower()
    if any(marker in lowered for marker in AI_POLICY_REJECT_MARKERS):
        return "reject"
    if any(marker in lowered for marker in AI_POLICY_DISCLOSE_MARKERS):
        return "disclose"
    if any(marker in lowered for marker in AI_POLICY_CONSTRAIN_MARKERS):
        return "constrain"
    return None


def screen_issue(
    owner: str,
    repo: str,
    number: int,
    client: GitHubReader,
    known_signed_orgs: frozenset[str] = frozenset(),
) -> ScreenResult:
    issue = client.get_issue(owner, repo, number)
    if issue is None:
        return ScreenResult(owner, repo, number, Verdict.NOT_FOUND, ["issue not found"])

    reasons: list[str] = []
    evidence: dict = {"title": issue.get("title"), "state": issue.get("state")}

    assignees = [a["login"] for a in (issue.get("assignees") or [])]
    if assignees:
        evidence["assignees"] = assignees
        reasons.append(f"assigned to {', '.join(assignees)}")

    duplicate_prs = _find_duplicate_prs(client.get_issue_timeline(owner, repo, number))
    if duplicate_prs:
        evidence["duplicate_prs"] = duplicate_prs
        reasons.append(f"{len(duplicate_prs)} PR(s) already reference this issue")

    contribution_norm = None
    contributing_text = ""
    for path in CONTRIBUTING_PATHS:
        text = client.get_repo_file_text(owner, repo, path)
        if text:
            evidence["contributing_path"] = path
            contributing_text = text
            contribution_norm = _detect_contribution_norm(text)
            break
    if contribution_norm:
        evidence["contribution_norm"] = contribution_norm

    # AI-contribution policy: checked against CONTRIBUTING.md (already
    # fetched above, real orgs state it there, e.g. paperless-ngx) and
    # AGENTS.md (a second, separate fetch — the file this exists
    # specifically for on many repos).
    ai_policy_text = contributing_text
    for path in AGENTS_PATHS:
        text = client.get_repo_file_text(owner, repo, path)
        if text:
            evidence["agents_path"] = path
            ai_policy_text = f"{ai_policy_text}\n{text}"
            break
    ai_policy = _detect_ai_contribution_policy(ai_policy_text) if ai_policy_text else None
    if ai_policy:
        evidence["ai_contribution_policy"] = ai_policy

    if duplicate_prs:
        verdict = Verdict.DUPLICATE
    elif assignees:
        verdict = Verdict.ASSIGNED
    elif ai_policy == "reject":
        verdict = Verdict.AI_POLICY_REJECT
        reasons.append("repo states it does not accept AI-generated contributions")
    elif contribution_norm == "cla" and owner.lower() not in known_signed_orgs:
        verdict = Verdict.CLA_REQUIRED
        reasons.append("CONTRIBUTING.md requires a CLA and this org isn't in known_signed_orgs")
    else:
        verdict = Verdict.CLEAR
        if ai_policy == "disclose":
            reasons.append("repo requires AI-assisted contributions to be disclosed — say so in the PR body")
        elif ai_policy == "constrain":
            reasons.append("repo requires the contributor to understand AI-generated code end-to-end before submitting")

    return ScreenResult(owner, repo, number, verdict, reasons, evidence)
