#!/usr/bin/env python
"""Benchmark hermes-trace validation against a Python streaming scan.

This script generates deterministic append-only trace JSONL and reports compact
JSON timings. It is intentionally dependency-free so it can run on developer
machines and CI without benchmark frameworks.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import statistics
import subprocess
import tempfile
import time
from pathlib import Path
from typing import Any

SUMMARY_KEYS = (
    "turns",
    "steps",
    "tool_calls",
    "tool_errors",
    "input_tokens",
    "output_tokens",
)


def event_for_seq(seq: int) -> dict[str, Any]:
    if seq == 1:
        event_type = "turn/start"
        data: dict[str, Any] = {}
    elif seq % 5 == 0:
        event_type = "tool/call"
        data = {"call_id": f"call-{seq}"}
    elif seq % 5 == 1:
        event_type = "tool/result"
        data = {"call_id": f"call-{seq - 1}", "is_error": seq % 10 == 6}
    else:
        event_type = "step/start"
        data = {}

    data["input_tokens"] = seq - 1
    data["output_tokens"] = 4 if seq % 2 == 0 else 0
    return {
        "schema_version": 1,
        "seq": seq,
        "time": 1_700_000_000.0 + seq,
        "session_id": "bench-session",
        "type": event_type,
        "turn": 1,
        "step": seq,
        "data": data,
    }


def write_trace(path: Path, events: int) -> None:
    if events <= 0:
        raise ValueError("events must be positive")
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        for seq in range(1, events + 1):
            handle.write(json.dumps(event_for_seq(seq), separators=(",", ":")))
            handle.write("\n")


def empty_summary() -> dict[str, int]:
    return {key: 0 for key in SUMMARY_KEYS}


def scan_trace_python(path: Path) -> dict[str, int]:
    summary = empty_summary()
    previous_seq = 0
    with path.open("r", encoding="utf-8") as handle:
        for line_number, raw in enumerate(handle, start=1):
            if not raw.strip():
                continue
            event = json.loads(raw)
            seq = int(event["seq"])
            if seq <= previous_seq:
                raise ValueError(f"non-monotonic sequence at line {line_number}")
            previous_seq = seq
            data = event.get("data") or {}
            event_type = event.get("type")
            if event_type == "turn/start":
                summary["turns"] += 1
            elif event_type == "step/start":
                summary["steps"] += 1
            elif event_type == "tool/call":
                if not data.get("call_id"):
                    raise ValueError(f"missing call_id at line {line_number}")
                summary["tool_calls"] += 1
            elif event_type == "tool/result":
                if not data.get("call_id"):
                    raise ValueError(f"missing call_id at line {line_number}")
                if data.get("is_error") is True:
                    summary["tool_errors"] += 1
            summary["input_tokens"] += int(data.get("input_tokens") or 0)
            summary["output_tokens"] += int(data.get("output_tokens") or 0)
    return summary


def time_call(fn, runs: int, warmups: int = 0) -> list[float]:
    for _ in range(warmups):
        fn()
    timings = []
    for _ in range(runs):
        started = time.perf_counter()
        fn()
        timings.append((time.perf_counter() - started) * 1000.0)
    return timings


RUST_COMMANDS = ("verify", "summary", "digest")
DIGEST_RE = re.compile(r"[0-9a-f]{64}")


def run_rust_command(binary: Path, command: str, trace_path: Path) -> None:
    completed = subprocess.run(
        [str(binary), command, str(trace_path)],
        check=False,
        capture_output=True,
        text=True,
    )
    if completed.returncode != 0:
        raise RuntimeError(completed.stderr.strip() or completed.stdout.strip())


def add_rust_command_timings(
    result: dict[str, Any],
    binary: Path,
    trace_path: Path,
    *,
    runs: int,
    warmups: int,
    runner=run_rust_command,
) -> None:
    result["rust_verify_binary"] = str(binary)
    for command in RUST_COMMANDS:
        timings = time_call(
            lambda command=command: runner(binary, command, trace_path),
            runs,
            warmups,
        )
        result[f"rust_{command}_ms_median"] = statistics.median(timings)
        result[f"rust_{command}_ms_runs"] = timings


def snapshot_digest_python(path: Path) -> str:
    """Return the Rust-compatible digest for benchmark/preflight trace shapes.

    This helper is intentionally scoped to the deterministic traces generated by
    this script. Python's JSON encoder is not byte-for-byte equivalent to
    serde_json for every JSON number spelling, so float values inside event data
    fail closed instead of producing a plausible but wrong digest.
    """
    hasher = hashlib.sha256()
    hasher.update(b"hermes-trace-snapshot-v1\n")
    with path.open("r", encoding="utf-8") as handle:
        for raw in handle:
            if not raw.strip():
                continue
            event = json.loads(raw)
            record = {
                "seq": event["seq"],
                "type": event["type"],
                "turn": event.get("turn"),
                "step": event.get("step"),
                "data": canonical_json_value(event.get("data")),
            }
            hasher.update(
                json.dumps(
                    record,
                    ensure_ascii=False,
                    separators=(",", ":"),
                ).encode("utf-8")
            )
            hasher.update(b"\n")
    return hasher.hexdigest()


def canonical_json_value(value):
    if isinstance(value, dict):
        return {key: canonical_json_value(value[key]) for key in sorted(value)}
    if isinstance(value, list):
        return [canonical_json_value(item) for item in value]
    if isinstance(value, float):
        raise ValueError(
            "float JSON values are not supported by the Python digest preflight"
        )
    return value


def preflight_output_is_valid(command: str, output: str, trace_path: Path) -> bool:
    output = output.strip()
    if command == "verify":
        return output == "ok"
    if command == "summary":
        try:
            return json.loads(output) == scan_trace_python(trace_path)
        except (json.JSONDecodeError, ValueError, TypeError):
            return False
    if command == "digest":
        return output == snapshot_digest_python(trace_path) and DIGEST_RE.fullmatch(output) is not None
    return False


def require_existing_binary(parser: argparse.ArgumentParser, binary: Path) -> None:
    if not binary.exists():
        parser.error(f"required binary not found: {binary}")
    if not binary.is_file():
        parser.error(f"required binary is not a file: {binary}")
    with tempfile.TemporaryDirectory(prefix="hermes-trace-preflight-") as temp_dir:
        trace_path = Path(temp_dir) / "trace.jsonl"
        write_trace(trace_path, events=1)
        for command in RUST_COMMANDS:
            try:
                completed = subprocess.run(
                    [str(binary), command, str(trace_path)],
                    check=False,
                    capture_output=True,
                    text=True,
                    timeout=5,
                )
            except (OSError, subprocess.TimeoutExpired) as exc:
                parser.error(f"required binary is not runnable: {binary}: {exc}")
            if completed.returncode != 0:
                detail = completed.stderr.strip() or completed.stdout.strip()
                parser.error(
                    f"required binary failed hermes-trace preflight ({command}): "
                    f"{binary}: {detail}"
                )
            if not preflight_output_is_valid(command, completed.stdout, trace_path):
                parser.error(
                    f"required binary failed hermes-trace preflight ({command}): "
                    f"{binary}: unexpected output"
                )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--events", type=int, default=100_000)
    parser.add_argument("--runs", type=int, default=5)
    parser.add_argument(
        "--warmups",
        type=int,
        default=1,
        help="Warmup executions before measured runs, useful for excluding process cold-start outliers.",
    )
    parser.add_argument(
        "--binary",
        type=Path,
        default=Path(__file__).resolve().parents[1]
        / "crates"
        / "hermes-trace"
        / "target"
        / "release"
        / ("hermes-trace.exe" if __import__("os").name == "nt" else "hermes-trace"),
        help=(
            "Path to the release hermes-trace binary. Build it first with "
            "`cargo build --release --manifest-path crates/hermes-trace/Cargo.toml`. "
            "If the binary is absent, the benchmark reports rust_verify_skipped."
        ),
    )
    parser.add_argument("--trace", type=Path)
    parser.add_argument(
        "--require-binary",
        action="store_true",
        help="Fail instead of reporting rust_*_skipped when the hermes-trace binary is missing.",
    )
    args = parser.parse_args()
    if args.runs <= 0:
        parser.error("--runs must be positive")
    if args.warmups < 0:
        parser.error("--warmups must not be negative")
    if args.require_binary:
        require_existing_binary(parser, args.binary)

    trace_path = args.trace or Path(tempfile.gettempdir()) / "hermes-trace-bench.jsonl"
    write_trace(trace_path, args.events)
    summary = scan_trace_python(trace_path)
    python_ms = time_call(lambda: scan_trace_python(trace_path), args.runs, args.warmups)

    result: dict[str, Any] = {
        "events": args.events,
        "runs": args.runs,
        "warmups": args.warmups,
        "trace": str(trace_path),
        "trace_bytes": trace_path.stat().st_size,
        "summary": summary,
        "python_scan_ms_median": statistics.median(python_ms),
        "python_scan_ms_runs": python_ms,
    }

    if args.binary.exists():
        add_rust_command_timings(
            result,
            args.binary,
            trace_path,
            runs=args.runs,
            warmups=args.warmups,
        )
    else:
        result["rust_verify_skipped"] = f"binary not found: {args.binary}"

    print(json.dumps(result, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
