"""Graph-gated owner generated by the #82591 campaign."""

# Probe and status helpers extracted from auxiliary_client.py.

import contextlib
import logging
from typing import Optional

logger = logging.getLogger("agent.auxiliary_client")  # pin god module name


def _aux_probe_active() -> bool:
    from agent.auxiliary_client import _aux_probe_state  # late import to avoid cycle
    return bool(getattr(_aux_probe_state, "active", False))


@contextlib.contextmanager
def aux_probe_mode():
    """Resolve provider availability without constructing real SDK clients."""
    from agent.auxiliary_client import _aux_probe_state  # late import to avoid cycle
    prev = getattr(_aux_probe_state, "active", False)
    _aux_probe_state.active = True
    try:
        yield
    finally:
        _aux_probe_state.active = prev


def _aux_interrupt_protected() -> bool:
    from agent.auxiliary_client import _aux_interrupt_protection  # late import
    return bool(getattr(_aux_interrupt_protection, "active", False))


def _aux_interrupt_cancel_requested() -> bool:
    """Return whether an explicit host cancel overrides aux protection."""
    from agent.auxiliary_client import _aux_interrupt_protection  # late import
    event = getattr(_aux_interrupt_protection, "cancel_event", None)
    if event is not None:
        try:
            return bool(event.is_set())
        except Exception:
            logger.debug("aux interrupt cancel event check failed", exc_info=True)
            return False
    check = getattr(_aux_interrupt_protection, "cancel_check", None)
    if not callable(check):
        return False
    try:
        return bool(check())
    except Exception:
        logger.debug("aux interrupt cancel check failed", exc_info=True)
        return False


def _aux_progress_active() -> bool:
    from agent.auxiliary_client import _aux_progress  # late import to avoid cycle
    return getattr(_aux_progress, "hook", None) is not None


@contextlib.contextmanager
def aux_progress_hook(hook):
    """Install *hook* as the current thread's aux forward-progress callback.

    ``hook=None`` is a no-op passthrough so callers can wire it
    unconditionally. Re-entrant-safe: restores the previous hook on exit.
    """
    from agent.auxiliary_client import _aux_progress  # late import to avoid cycle
    prev = getattr(_aux_progress, "hook", None)
    _aux_progress.hook = hook if callable(hook) else prev
    try:
        yield
    finally:
        _aux_progress.hook = prev


def _aux_stream_total_ceiling(effective_timeout: Optional[float]) -> float:
    """Absolute wall-clock bound for a progress-hooked streamed aux call.

    Generous by design — the idle timeout is the real guard; this only stops
    a degenerate stream that trickles one token per idle window forever.
    """
    from agent.auxiliary_client import (  # late import to avoid cycle
        _AUX_STREAM_CEILING_FLOOR_SECONDS,
        _AUX_STREAM_CEILING_MULTIPLIER,
    )
    try:
        timeout = float(effective_timeout) if effective_timeout is not None else 0.0
    except (TypeError, ValueError):
        timeout = 0.0
    return max(_AUX_STREAM_CEILING_FLOOR_SECONDS,
               _AUX_STREAM_CEILING_MULTIPLIER * timeout)
