"""Graph-gated owner generated by the #82591 campaign."""

# Provider classification and normalization helpers.

import os
from typing import Any, Dict, Optional


def _normalize_aux_provider(provider: Optional[str]) -> str:
    from agent.auxiliary_client import (  # late import to avoid cycle
        _PROVIDER_ALIASES,
        _read_main_provider,
    )
    normalized = (provider or "auto").strip().lower()
    if normalized.startswith("custom:"):
        suffix = normalized.split(":", 1)[1].strip()
        if not suffix:
            return "custom"
        normalized = suffix
    if normalized == "codex":
        return "openai-codex"
    if normalized == "main":
        # Resolve to the user's actual main provider so named custom providers
        # and non-aggregator providers (DeepSeek, Alibaba, etc.) work correctly.
        main_prov = (_read_main_provider() or "").strip().lower()
        if main_prov and main_prov not in {"auto", "main", ""}:
            normalized = main_prov
        else:
            return "custom"
    return _PROVIDER_ALIASES.get(normalized, normalized)


def _is_kimi_model(model: Optional[str]) -> bool:
    """True for any Kimi / Moonshot model that manages temperature server-side."""
    bare = (model or "").strip().lower().rsplit("/", 1)[-1]
    return bare.startswith("kimi-") or bare == "kimi"


def _is_arcee_trinity_thinking(model: Optional[str]) -> bool:
    """True for Arcee Trinity Large Thinking (direct or via OpenRouter)."""
    bare = (model or "").strip().lower().rsplit("/", 1)[-1]
    return bare == "trinity-large-thinking"


def _nous_base_url() -> str:
    """Resolve the Nous inference base URL from env or default."""
    from agent.auxiliary_client import _NOUS_DEFAULT_BASE_URL  # late import
    return os.getenv("NOUS_INFERENCE_BASE_URL", _NOUS_DEFAULT_BASE_URL)


def _is_free_model(model: Optional[str]) -> bool:
    """True when ``model`` is an OpenRouter free SKU (``:free`` suffix)."""
    return bool(model) and str(model).strip().endswith(":free")


def _current_custom_base_url() -> str:
    from agent.auxiliary_client import _resolve_custom_runtime  # late import
    custom_base, _, _ = _resolve_custom_runtime()
    return custom_base or ""


def _normalize_main_runtime(main_runtime: Optional[Dict[str, Any]]) -> Dict[str, Any]:
    """Return a sanitized copy of a live main-runtime override.

    Most fields are stripped strings. ``api_key`` may legitimately be a
    zero-arg callable (Azure Foundry Entra ID token provider) — preserve
    those as-is so auxiliary clients inherit the same authentication
    surface as the main agent. The OpenAI SDK accepts ``Callable[[], str]``
    for ``api_key`` and calls it before every request.
    """
    if main_runtime is None:
        # Context-local state is inherited by tool worker wrappers while
        # remaining isolated across concurrent gateway sessions. Never fall
        # back to compatibility mirrors here: another session may have written
        # them most recently, which would leak its endpoint/key into this call.
        from agent.auxiliary_client import (  # late import to avoid cycle
            _RUNTIME_MAIN_CONTEXT,
            _compat_runtime_main,
        )
        main_runtime = _RUNTIME_MAIN_CONTEXT.get()
        if main_runtime is None:
            main_runtime = _compat_runtime_main()
    if not isinstance(main_runtime, dict):
        return {}
    from agent.auxiliary_client import _MAIN_RUNTIME_CONTEXT_FIELDS  # late import
    normalized: Dict[str, Any] = {}
    for field in _MAIN_RUNTIME_CONTEXT_FIELDS:
        value = main_runtime.get(field)
        # Preserve a callable api_key (Entra ID bearer provider) unchanged.
        if field == "api_key" and callable(value) and not isinstance(value, str):
            normalized[field] = value
            continue
        if isinstance(value, str) and value.strip():
            normalized[field] = value.strip()
    for identity_field in ("provider", "requested_provider"):
        identity = normalized.get(identity_field)
        if isinstance(identity, str):
            normalized[identity_field] = identity.lower()
    return normalized


def _normalize_chain_label(provider: str) -> str:
    """Normalize a resolved_provider value to a chain label used by
    ``_get_provider_chain()``. Falls back to the lowercased input for
    direct API-key providers (deepseek, alibaba, minimax, etc.) which
    each report their own provider name from the api-key chain.
    """
    if not provider:
        return ""
    from agent.auxiliary_client import _AUX_UNHEALTHY_LABEL_ALIASES  # late import
    p = str(provider).strip().lower()
    return _AUX_UNHEALTHY_LABEL_ALIASES.get(p, p)


def _normalize_resolved_model(model_name: Optional[str], provider: str) -> Optional[str]:
    """Normalize a resolved model for the provider that will receive it."""
    if not model_name:
        return model_name
    try:
        from hermes_cli.model_normalize import normalize_model_for_provider

        return normalize_model_for_provider(model_name, provider)
    except Exception:
        return model_name


def _normalize_vision_provider(provider: Optional[str]) -> str:
    return _normalize_aux_provider(provider)


def _strict_vision_backend_available(provider: str) -> bool:
    from agent.auxiliary_client import _resolve_strict_vision_backend  # late import
    return _resolve_strict_vision_backend(provider)[0] is not None
