-- Hermes state.db mirror schema for MariaDB / MySQL.
-- One database per Hermes profile (or "hermes" for the default home).
-- All core tables carry a `machine` column so multiple machines can write
-- to the same database without id collisions.
-- Hermes state.db mirror schema for MariaDB

CREATE TABLE sessions (
    machine VARCHAR(64) NOT NULL,
    id VARCHAR(128) NOT NULL,
    source VARCHAR(64) NOT NULL,
    user_id VARCHAR(128),
    model VARCHAR(128),
    model_config LONGTEXT,
    system_prompt LONGTEXT,
    parent_session_id VARCHAR(128),
    started_at DOUBLE NOT NULL,
    ended_at DOUBLE,
    end_reason VARCHAR(64),
    message_count INT DEFAULT 0,
    tool_call_count INT DEFAULT 0,
    input_tokens BIGINT DEFAULT 0,
    output_tokens BIGINT DEFAULT 0,
    cache_read_tokens BIGINT DEFAULT 0,
    cache_write_tokens BIGINT DEFAULT 0,
    reasoning_tokens BIGINT DEFAULT 0,
    billing_provider VARCHAR(64),
    billing_base_url VARCHAR(255),
    billing_mode VARCHAR(32),
    estimated_cost_usd DOUBLE,
    actual_cost_usd DOUBLE,
    cost_status VARCHAR(32),
    cost_source VARCHAR(32),
    pricing_version VARCHAR(32),
    title VARCHAR(512),
    api_call_count INT DEFAULT 0,
    handoff_state TEXT,
    handoff_platform VARCHAR(64),
    handoff_error TEXT,
    cwd VARCHAR(512),
    rewind_count INT NOT NULL DEFAULT 0,
    archived INT NOT NULL DEFAULT 0,
    session_key VARCHAR(512),
    chat_id VARCHAR(128),
    chat_type VARCHAR(32),
    thread_id VARCHAR(128),
    display_name VARCHAR(255),
    origin_json LONGTEXT,
    expiry_finalized INT DEFAULT 0,
    git_branch VARCHAR(255),
    git_repo_root VARCHAR(512),
    compression_failure_cooldown_until DOUBLE,
    compression_failure_error TEXT,
    compression_fallback_streak INT NOT NULL DEFAULT 0,
    compression_ineffective_count INT NOT NULL DEFAULT 0,
    profile_name VARCHAR(64),
    pinned INT NOT NULL DEFAULT 0,
    PRIMARY KEY (machine, id),
    KEY idx_sessions_source (source),
    KEY idx_sessions_started (started_at),
    KEY idx_sessions_session_key (session_key),
    KEY idx_sessions_gateway_peer (source, user_id, chat_id, chat_type, thread_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE messages (
    machine VARCHAR(64) NOT NULL,
    id BIGINT NOT NULL,
    session_id VARCHAR(128) NOT NULL,
    role VARCHAR(32) NOT NULL,
    content LONGTEXT,
    tool_call_id VARCHAR(128),
    tool_calls LONGTEXT,
    tool_name VARCHAR(128),
    timestamp DOUBLE NOT NULL,
    token_count INT,
    finish_reason VARCHAR(64),
    reasoning LONGTEXT,
    reasoning_content LONGTEXT,
    reasoning_details LONGTEXT,
    codex_reasoning_items LONGTEXT,
    codex_message_items LONGTEXT,
    platform_message_id VARCHAR(128),
    observed INT DEFAULT 0,
    active INT NOT NULL DEFAULT 1,
    effect_disposition VARCHAR(64),
    compacted INT NOT NULL DEFAULT 0,
    api_content LONGTEXT,
    display_kind VARCHAR(64),
    display_metadata LONGTEXT,
    PRIMARY KEY (machine, id),
    KEY idx_messages_session (session_id, timestamp),
    KEY idx_messages_machine_session (machine, session_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE session_model_usage (
    machine VARCHAR(64) NOT NULL,
    session_id VARCHAR(128) NOT NULL,
    model VARCHAR(128) NOT NULL,
    billing_provider VARCHAR(64) NOT NULL DEFAULT '',
    billing_base_url VARCHAR(255) NOT NULL DEFAULT '',
    billing_mode VARCHAR(32) NOT NULL DEFAULT '',
    task VARCHAR(64) NOT NULL DEFAULT '',
    api_call_count INT NOT NULL DEFAULT 0,
    input_tokens BIGINT NOT NULL DEFAULT 0,
    output_tokens BIGINT NOT NULL DEFAULT 0,
    cache_read_tokens BIGINT NOT NULL DEFAULT 0,
    cache_write_tokens BIGINT NOT NULL DEFAULT 0,
    reasoning_tokens BIGINT NOT NULL DEFAULT 0,
    estimated_cost_usd DOUBLE NOT NULL DEFAULT 0,
    actual_cost_usd DOUBLE NOT NULL DEFAULT 0,
    cost_status VARCHAR(32),
    cost_source VARCHAR(32),
    first_seen DOUBLE,
    last_seen DOUBLE,
    PRIMARY KEY (machine, session_id, model, billing_provider, billing_base_url, billing_mode, task),
    KEY idx_usage_model (model)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE schema_version (
    version INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
