"""Repository capabilities for tools shipped by Hermes core.

This manifest is deliberately limited to built-ins. Plugin and MCP tools are
runtime extensions and must declare their own ``repo_access`` at registration;
looking them up here by name would let an override inherit trust from the core
tool it replaced.
"""

BUILTIN_REPO_ACCESS = {
    "annotate_preview": "none",
    "apply_layout": "none",
    "bfl_flux3_get_result": "none",
    "bfl_flux3_image_to_video": "none",
    "bfl_flux3_keyframes_to_video": "none",
    "bfl_flux3_prompting_guide": "none",
    "bfl_flux3_text_to_video": "none",
    "bfl_flux3_video_continuation": "none",
    "browser_back": "none",
    "browser_cdp": "none",
    "browser_click": "none",
    "browser_console": "none",
    "browser_dialog": "none",
    "browser_exec": "write",
    "browser_get_images": "none",
    "browser_navigate": "none",
    "browser_press": "none",
    "browser_scroll": "none",
    "browser_snapshot": "none",
    "browser_type": "none",
    "browser_vision": "none",
    "clarify": "none",
    "close_preview": "none",
    "close_terminal": "none",
    "computer_use": "write",
    # Schedules commands, so it is deferred shell access.
    "cronjob": "write",
    "delegate_task": "none",
    "discord": "none",
    "discord_admin": "none",
    "drive_preview": "none",
    "execute_code": "write",
    "feishu_doc_read": "none",
    "feishu_drive_add_comment": "none",
    "feishu_drive_list_comment_replies": "none",
    "feishu_drive_list_comments": "none",
    "feishu_drive_reply_comment": "none",
    "focus_pane": "none",
    "ha_call_service": "none",
    "ha_get_state": "none",
    "ha_list_entities": "none",
    "ha_list_services": "none",
    "image_generate": "none",
    "kanban_attach": "none",
    "kanban_attach_url": "none",
    "kanban_attachments": "none",
    "kanban_block": "none",
    "kanban_comment": "none",
    "kanban_complete": "none",
    "kanban_create": "none",
    "kanban_heartbeat": "none",
    "kanban_link": "none",
    "kanban_list": "none",
    "kanban_request_changes": "none",
    "kanban_request_review": "none",
    "kanban_show": "none",
    "kanban_unblock": "none",
    "memory": "none",
    "open_preview": "none",
    "patch": "write",
    # `write` and `submit` send arbitrary stdin to an attached process. A shell
    # may have started before routing was enabled or through another surface,
    # so withholding only `terminal` would still leave a command path. This
    # withholds read-only process actions too; splitting the tool is the route
    # to finer access because capability is not currently per action.
    "process": "write",
    "project_create": "none",
    "project_list": "none",
    "project_switch": "none",
    "react_to_message": "none",
    "read_file": "read",
    "read_preview": "none",
    "read_terminal": "none",
    "read_window_below": "none",
    "search_files": "read",
    "session_search": "none",
    "setup_mcp": "none",
    "skill_manage": "none",
    "skill_view": "none",
    "skills_list": "none",
    "terminal": "write",
    "text_to_speech": "none",
    "todo": "none",
    "tour": "none",
    "video_analyze": "none",
    "video_generate": "none",
    "vision_analyze": "none",
    "web_extract": "none",
    "web_search": "none",
    "write_file": "write",
    "x_search": "none",
    "xai_video_edit": "none",
    "xai_video_extend": "none",
    "yb_query_group_info": "none",
    "yb_query_group_members": "none",
    "yb_search_sticker": "none",
    "yb_send_dm": "none",
    "yb_send_sticker": "none",
}
