name: Trigger Tests

on:
  push:
    branches: [main]
    paths-ignore:
      - trigger.yml

jobs: 
  trigger: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@b7c7190bbe5b1630ceea73d27597364c9af683 #v4.2.2
        name: Run Tests
        run: echo "Triggered"
